//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace My_Shop.Core.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Product
    {
        public int Id { get; set; }
        [DisplayName("Product Name")]
        [StringLength(25)]
        public string Name { get; set; }
        public string Description { get; set; }
        [Range(0, 100)]
        public Nullable<decimal> Prize { get; set; }
        public string Category { get; set; }
        public byte[] Image { get; set; }
    }
}
